#!/bin/sh
/usr/sbin/ip6tables -I delegate_forward 1 -i $1 -j zone_client_forward
/usr/sbin/ip6tables -I delegate_input 1 -i $1 -j zone_client_input
/usr/sbin/ip6tables -I delegate_output 1 -i $1 -j zone_client_output
/usr/sbin/ip6tables -I zone_client_dest_ACCEPT 1 -o $1 -j ACCEPT
/usr/sbin/ip6tables -I zone_client_src_ACCEPT 1 -i $1 -j ACCEPT

