#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1
PROG=/usr/sbin/l3roamd

start_service () {
        procd_open_instance
        procd_set_param stdout 1
        procd_set_param stderr 1
        # TODO l3roamd should be enabled to change mesh interfaces and client interfaces dynamically
        procd_set_param command "$PROG" -p $(lua -e 'print(require("gluon.site_config").prefix6)') -i br-client -m mesh-vpn -m mesh0 -t 11 -a $(uci get network.loopback.ip6addr | cut -d/ -f1)
        procd_close_instance
}

